[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
arena = "oDDawv2GGcWhMCVjsxfBppYZUTp8XF1nGcqNUSFuFWL"

[programs.devnet]
arena = "oDDawv2GGcWhMCVjsxfBppYZUTp8XF1nGcqNUSFuFWL"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/**/*.ts"
